### ISSUE TITLE
Loras not working

### ISSUE THREAD

**Issue by eyetest42** [etherealxx/volatile-concentration-localux-colab#32]
Loras are 100% not working for me at all. is this another camenduru issue?

**Comment by zucced** [comment]
for some reason the loras are working fine on nightly but not on stable

**Comment by etherealxx** [comment]
Have you guys tried using additional networks? Do you have any copy/screenshots of the terminal?

**Comment by basedholychad** [comment]
yeah the nightly working fine, but the stable line not working,

**Comment by zucced** [comment]
> Have you guys tried using additional networks? Do you have any copy/screenshots of the terminal?

I actually don't use additional networks for loras, I use on prompt input directly like '<lora:LoraName:1>' and here's the error I get:

`
Total progress: 0it [00:00, ?it/s]locon load lora method
loading Lora /content/volatile-concentration-localux/models/Lora/LoraName.safetensors: TypeError
Traceback (most recent call last):
  File "/content/volatile-concentration-localux/extensions/a1111-sd-webui-locon/scripts/../../../extensions-builtin/Lora/lora.py", line 253, in load_loras
    lora = load_lora(name, lora_on_disk)
  File "/content/volatile-concentration-localux/extensions/a1111-sd-webui-locon/scripts/main.py", line 366, in load_lora
    lora.mtime = os.path.getmtime(filename)
  File "/usr/lib/python3.10/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
TypeError: stat: path should be string, bytes, os.PathLike or integer, not LoraOnDisk
`

**Comment by maxinzheng** [comment]
me too

====================
Traceback (most recent call last):
  File "/content/volatile-concentration-localux/extensions/a1111-sd-webui-locon/scripts/../../../extensions-builtin/Lora/lora.py", line 253, in load_loras
    lora = load_lora(name, lora_on_disk)
  File "/content/volatile-concentration-localux/extensions/a1111-sd-webui-locon/scripts/main.py", line 366, in load_lora
    lora.mtime = os.path.getmtime(filename)
  File "/usr/lib/python3.10/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
TypeError: stat: path should be string, bytes, os.PathLike or integer, not LoraOnDisk
====================
